### ISSUE TITLE
I can't build it, any idea ?

### ISSUE THREAD

**Issue by iamslan** [derpston/linux-rpi-audi-dis#1]
root@raspberrypi:~/linux-rpi-audi-dis-master# make
make -C /lib/modules/3.18.11+/build M=/root/linux-rpi-audi-dis-master modules
make[1]: Entering directory '/usr/src/linux-headers-3.18.11+'
  CC [M]  /root/linux-rpi-audi-dis-master/dis.o
/root/linux-rpi-audi-dis-master/dis.c: In function ‘dis_init’:
/root/linux-rpi-audi-dis-master/dis.c:172:5: error: implicit declaration of function ‘create_proc_entry’ [-Werror=implicit-function-declaration]
/root/linux-rpi-audi-dis-master/dis.c:172:22: warning: assignment makes pointer from integer without a cast [enabled by default]
/root/linux-rpi-audi-dis-master/dis.c:173:21: error: dereferencing pointer to incomplete type
cc1: some warnings being treated as errors
scripts/Makefile.build:263: recipe for target '/root/linux-rpi-audi-dis-master/dis.o' failed
make[2]: **\* [/root/linux-rpi-audi-dis-master/dis.o] Error 1
Makefile:1381: recipe for target '_module_/root/linux-rpi-audi-dis-master' failed
make[1]: **\* [_module_/root/linux-rpi-audi-dis-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.18.11+'
Makefile:8: recipe for target 'dis' failed
make: **\* [dis] Error 2

**Comment by iamslan** [comment]
FYI, I'm running a 3.18 kernel.

proc_fs.h seems to have changed since 3.10 kernel : create_proc_entry is deprecated 
-> use proc_create instead

I'm now having another error related with this line :
"proc_write_entry->write_proc = write_proc;"

write_proc seems to be deprecated too... but I can't find the needed replacement.

Make log :

root@raspberrypi:~/linux-rpi-audi-dis-master# make
make -C /lib/modules/3.18.11+/build M=/root/linux-rpi-audi-dis-master modules
make[1]: Entering directory '/usr/src/linux-headers-3.18.11+'
  CC [M]  /root/linux-rpi-audi-dis-master/dis.o
/root/linux-rpi-audi-dis-master/dis.c: In function ‘dis_init’:
/root/linux-rpi-audi-dis-master/dis.c:173:21: error: dereferencing pointer to incomplete type
scripts/Makefile.build:263: recipe for target '/root/linux-rpi-audi-dis-master/dis.o' failed
make[2]: **\* [/root/linux-rpi-audi-dis-master/dis.o] Error 1
Makefile:1381: recipe for target '_module_/root/linux-rpi-audi-dis-master' failed
make[1]: **\* [_module_/root/linux-rpi-audi-dis-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.18.11+'
Makefile:8: recipe for target 'dis' failed
make: **\* [dis] Error 2

PS : Sorry, I have a very poor knowledge of linux and kernel development.

**Comment by iamslan** [comment]
Thanks for your work :)

Testing it very soon !

![rpi ready to test](http://upload.streetlegal.fr/upload/server/php/files/image%20%2828%29.jpg)

**Comment by derpston** [comment]
Nice! Please send a picture of the result when it works!

I like the in-place documentation, that looks very useful.

**Comment by iamslan** [comment]
Here are the pictures, but I'll need some more help! :-)

I'm looking at voltages when DIS module is loaded:
- CLOCK/GND: ~5V
- DATA/GND: ~5V
- ENABLED/GND: ~0V

![rpi gpio voltage](http://upload.streetlegal.fr/upload/server/php/files/IMG_1315.jpg)

I'm executing a simple script sending a message every second.
I don't have any oscilloscope to monitor precisely, but I can see changes every second on voltages :
- CLOCK/GND: Moving down then back to ~5V
- DATA/GND: Moving down then back to ~5V
- ENABLED/GND: Moving up then back to ~0V

So it looks to be working nicely, but when connecting to the car...

![rpi gpio connected to the car](http://upload.streetlegal.fr/upload/server/php/files/IMG_1309.jpg)

...DIS is staying off :-(

![car dis still off](http://upload.streetlegal.fr/upload/server/php/files/IMG_1311.jpg)

What checks should I do?

Thanks for your help!

**Comment by derpston** [comment]
The behaviour you're seeing with the multimeter sounds correct, but without an oscilloscope or logic analyser it's difficult to figure out what's wrong. If we assume the code is doing the right thing (and I think it probably is, I don't think you changed any of the business logic) the most obvious problem is simply getting the wiring wrong, but I have to assume you double checked that. My documentation may be wrong, I'll try to check that.

Can I see the message or the script that you're using to write to /proc/dis? I found that some messages are ignored by the DIS.

I usually test with something like:

``` shell
echo -n "TEST" > /proc/dis
```

**Comment by derpston** [comment]
You might also want to make sure that the RPi's ground is the same as the car's ground. If they're even a little different, the SPI messages will be corrupt in some way and will be ignored.

**Comment by iamslan** [comment]
My bad, again...

Wiring was wrong : CLK,DATA,ENA were reversed. Ground was already connected to car ground, I read your advertising!

Everything is working so good ; I'll be working on getting engine measures via OBD2 now.

Thanks again!

![Everything working good](http://upload.streetlegal.fr/upload/server/php/files/Capture%20d%E2%80%99%C3%A9cran%202015-04-25%20%C3%A0%2023.19.27.png)

**Comment by derpston** [comment]
Excellent, well done! I'm very glad it works for someone other than myself. :)

I also intend to put some engine stats there, except I'm not satisfied with what is available over OBD2 and I'll need to find or write an interface for KWP2000/ISO14230 to get the really interesting stats, like turbo pressures, air flow rates, etc. [VCDS](http://www.ross-tech.com/) can get that data, but last time I looked I couldn't find any embeddable open source libraries for doing similar work.

I have an ECU from a similar car on my desk, maybe one day I'll get around to this. :)

**Comment by iamslan** [comment]
I'll try some things with my VCDS and ELM327 USB.

Just a small issue ; some "j" coming from nowhere :-p They're not in what I echoed to /proc/dis.

![small issue](http://upload.streetlegal.fr/upload/server/php/files/Capture%20d%E2%80%99%C3%A9cran%202015-04-26%20%C3%A0%2000.10.10.png)

**Comment by derpston** [comment]
Try `echo -n` to suppress the newline, I saw similar behaviour.

**Comment by iamslan** [comment]
:+1:
